### ISSUE TITLE
Cannot find name 'Omit'

### ISSUE THREAD

**Issue by arcovoltaico** [fent/node-ytdl-core#644]
After updating to 3.1.0 I'm getting this error when npm start

ERROR in node_modules/ytdl-core/typings/index.d.ts(163,40): error TS2304: Cannot find name 'Omit'.
node_modules/ytdl-core/typings/index.d.ts(163,70): error TS2304: Cannot find name 'Omit'.

**Comment by arcovoltaico** [comment]
Fixed by updating:  "typescript": "3.5.3",
